server:
  port: 9000
  servlet:
    context-path: /enterprise-control

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true